import React from 'react'

import { ComponentStory, ComponentMeta } from '@storybook/react'

import FacetList from './FacetList'

// default
export default {
  title: 'Filter-By/FacetList',
  component: FacetList,
} as ComponentMeta<typeof FacetList>

const Template: ComponentStory<typeof FacetList> = (args) => <FacetList {...args} />

// Common
export const Common = Template.bind({})

const facetList = [
  {
    label: 'Category',
    facetType: 'Hierarchy',
    field: 'CategoryId',
    values: [
      {
        label: 'Skiing',
        value: '1',
        filterValue: 'categoryId:1',
        isDisplayed: true,
        count: 30,
        isApplied: null,
        childrenFacetValues: [
          {
            label: 'Ski Jackets',
            count: 15,
            value: '16',
            filterValue: 'categoryId:16',
            isDisplayed: true,
          },
        ],
      },
      {
        label: 'Apparel',
        value: '4',
        filterValue: 'categoryId:4',
        isDisplayed: true,
        count: 30,
        isApplied: null,
        childrenFacetValues: [
          {
            label: 'Jackets',
            count: 15,
            value: '24',
            filterValue: 'categoryId:24',
            isDisplayed: true,
          },
        ],
      },
    ],
  },
  {
    label: 'Gender',
    facetType: 'Value',
    field: 'Tenant~gender',
    values: [
      {
        label: 'Men',
        value: 'men',
        filterValue: 'Tenant~gender:men',
        isDisplayed: true,
        count: 8,
        isApplied: false,
        childrenFacetValues: null,
      },
      {
        label: 'Women',
        value: 'women',
        filterValue: 'Tenant~gender:women',
        isDisplayed: true,
        count: 7,
        isApplied: false,
        childrenFacetValues: null,
      },
      {
        label: 'Kids',
        value: 'kids',
        filterValue: 'Tenant~gender:kids',
        isDisplayed: true,
        count: 3,
        isApplied: false,
        childrenFacetValues: null,
      },
    ],
  },
  {
    label: 'Category',
    facetType: 'Hierarchy',
    field: 'CategoryCode',
    values: [
      {
        label: 'Jackets',
        value: '53',
        filterValue: 'categoryCode:53',
        isDisplayed: true,
        count: 15,
        isApplied: null,
        childrenFacetValues: null,
      },
    ],
  },
  {
    label: 'Color',
    facetType: 'Value',
    field: 'Tenant~color',
    values: [
      {
        label: 'Black',
        value: 'black',
        filterValue: 'Tenant~color:black',
        isDisplayed: true,
        count: 8,
        isApplied: false,
        childrenFacetValues: null,
      },
      {
        label: 'Blue',
        value: 'blue',
        filterValue: 'Tenant~color:blue',
        isDisplayed: true,
        count: 5,
        isApplied: false,
        childrenFacetValues: null,
      },
      {
        label: 'Green',
        value: 'green',
        filterValue: 'Tenant~color:green',
        isDisplayed: true,
        count: 2,
        isApplied: false,
        childrenFacetValues: null,
      },
      {
        label: 'Grey',
        value: 'grey',
        filterValue: 'Tenant~color:grey',
        isDisplayed: true,
        count: 4,
        isApplied: false,
        childrenFacetValues: null,
      },
      {
        label: 'Orange',
        value: 'orange',
        filterValue: 'Tenant~color:orange',
        isDisplayed: true,
        count: 1,
        isApplied: false,
        childrenFacetValues: null,
      },
      {
        label: 'Pink',
        value: 'pink',
        filterValue: 'Tenant~color:pink',
        isDisplayed: true,
        count: 2,
        isApplied: false,
        childrenFacetValues: null,
      },
      {
        label: 'Purple',
        value: 'purple',
        filterValue: 'Tenant~color:purple',
        isDisplayed: true,
        count: 2,
        isApplied: false,
        childrenFacetValues: null,
      },
      {
        label: 'Red',
        value: 'red',
        filterValue: 'Tenant~color:red',
        isDisplayed: true,
        count: 5,
        isApplied: false,
        childrenFacetValues: null,
      },
      {
        label: 'Silver',
        value: 'silver',
        filterValue: 'Tenant~color:silver',
        isDisplayed: true,
        count: 1,
        isApplied: false,
        childrenFacetValues: null,
      },
      {
        label: 'Teal',
        value: 'teal',
        filterValue: 'Tenant~color:teal',
        isDisplayed: true,
        count: 1,
        isApplied: false,
        childrenFacetValues: null,
      },
      {
        label: 'Yellow',
        value: 'yellow',
        filterValue: 'Tenant~color:yellow',
        isDisplayed: true,
        count: 2,
        isApplied: false,
        childrenFacetValues: null,
      },
    ],
  },
  {
    label: 'Price',
    facetType: 'RangeQuery',
    field: 'Price',
    values: [
      {
        label: '50 to 100',
        value: 'price:[50 TO 100]',
        filterValue: 'price:[50 TO 100]',
        isDisplayed: true,
        count: 1,
        isApplied: false,
        childrenFacetValues: null,
      },
      {
        label: '100 to 500',
        value: 'price:[100 TO 500]',
        filterValue: 'price:[100 TO 500]',
        isDisplayed: true,
        count: 14,
        isApplied: false,
        childrenFacetValues: null,
      },
    ],
  },
  {
    label: 'Brand',
    facetType: 'Value',
    field: 'Tenant~brand',
    values: [
      {
        label: 'Arctyex',
        value: 'arctyex',
        filterValue: 'Tenant~brand:arctyex',
        isDisplayed: true,
        count: 1,
        isApplied: false,
        childrenFacetValues: null,
      },
      {
        label: 'Burton',
        value: 'burton',
        filterValue: 'Tenant~brand:burton',
        isDisplayed: true,
        count: 1,
        isApplied: false,
        childrenFacetValues: null,
      },
      {
        label: 'Columbia',
        value: 'columbia',
        filterValue: 'Tenant~brand:columbia',
        isDisplayed: true,
        count: 2,
        isApplied: false,
        childrenFacetValues: null,
      },
      {
        label: 'Marmont',
        value: 'marmont',
        filterValue: 'Tenant~brand:marmont',
        isDisplayed: true,
        count: 1,
        isApplied: false,
        childrenFacetValues: null,
      },
      {
        label: 'Mystic',
        value: 'mystic',
        filterValue: 'Tenant~brand:mystic',
        isDisplayed: true,
        count: 4,
        isApplied: false,
        childrenFacetValues: null,
      },
      {
        label: 'Patagonia',
        value: 'patagonia',
        filterValue: 'Tenant~brand:patagonia',
        isDisplayed: true,
        count: 2,
        isApplied: false,
        childrenFacetValues: null,
      },
      {
        label: 'Salomon',
        value: 'salomon',
        filterValue: 'Tenant~brand:salomon',
        isDisplayed: true,
        count: 1,
        isApplied: false,
        childrenFacetValues: null,
      },
      {
        label: 'The North Face',
        value: 'the-north-face',
        filterValue: 'Tenant~brand:the-north-face',
        isDisplayed: true,
        count: 3,
        isApplied: false,
        childrenFacetValues: null,
      },
    ],
  },
]
Common.args = {
  facetList,
}
