export { default as B2BProductSearch } from '@/components/b2b/B2BProductSearch/B2BProductSearch'
export { default as B2BProductDetailsTable } from '@/components/b2b/B2BProductDetailsTable/B2BProductDetailsTable'
export { default as QuotesCommentThread } from '@/components/b2b/QuotesCommentThread/QuotesCommentThread'
export { default as QuotesTable } from '@/components/b2b/QuotesTable/QuotesTable'
export { default as QuotesHistory } from '@/components/b2b/QuotesHistory/QuotesHistory'
