import type { CategoryCollection, PrCategory } from '@/lib/gql/types'

export const categoryTreeDataMock: { categoriesTree: CategoryCollection } = {
  categoriesTree: {
    items: [
      {
        count: 28,
        updateDate: '',
        categoryId: 1,
        categoryCode: 'M',
        isDisplayed: null,
        content: {
          name: 'Men',
          slug: 'mens',
          description: 'Mens stuff',
        },
        childrenCategories: [
          {
            count: 0,
            updateDate: '',
            categoryId: 17,
            categoryCode: 'MS',
            isDisplayed: true,
            content: {
              name: 'Swim',
              slug: 'swim',
              description: 'Marco! Marco!',
            },
            childrenCategories: [],
          },
          {
            count: 14,
            updateDate: '',
            categoryId: 15,
            categoryCode: 'MA',
            isDisplayed: true,
            content: {
              name: 'Active',
              slug: 'active',
              description: 'Be like an old spice commercial',
            },
            childrenCategories: [
              {
                count: 3,
                updateDate: '',
                categoryId: 33,
                categoryCode: 'MAF',
                isDisplayed: true,
                content: {
                  name: 'Footwear',
                  slug: 'footwear',
                  description: '',
                },
                childrenCategories: [],
              },
              {
                count: 10,
                updateDate: '',
                categoryId: 31,
                categoryCode: 'MAT',
                isDisplayed: true,
                content: {
                  name: 'Shirts',
                  slug: 'tops',
                  description: '',
                },
                childrenCategories: [],
              },
              {
                count: 1,
                updateDate: '',
                categoryId: 30,
                categoryCode: 'MAB',
                isDisplayed: true,
                content: {
                  name: 'Bottoms',
                  slug: 'bottoms',
                  description: '',
                },
                childrenCategories: [],
              },
            ],
          },
          {
            count: 14,
            updateDate: '',
            categoryId: 21,
            categoryCode: 'MC',
            isDisplayed: true,
            content: {
              name: 'Casual',
              slug: 'casual',
              description: 'Because sweating is overrated',
            },
            childrenCategories: [
              {
                count: 1,
                updateDate: '',
                categoryId: 35,
                categoryCode: 'MCB',
                isDisplayed: true,
                content: {
                  name: 'Bottoms',
                  slug: 'bottoms',
                  description: '',
                },
                childrenCategories: [],
              },
              {
                count: 3,
                updateDate: '',
                categoryId: 32,
                categoryCode: 'MCF',
                isDisplayed: true,
                content: {
                  name: 'Footwear',
                  slug: 'footwear',
                  description: '',
                },
                childrenCategories: [],
              },
              {
                count: 10,
                updateDate: '',
                categoryId: 34,
                categoryCode: 'MCT',
                isDisplayed: true,
                content: {
                  name: 'Shirts',
                  slug: 'tops',
                  description: '',
                },
                childrenCategories: [],
              },
            ],
          },
        ],
      },
      {
        count: 21,
        updateDate: '',
        categoryId: 2,
        categoryCode: '27',
        isDisplayed: true,
        content: {
          name: 'Camping',
          slug: 'camping',
          description: '',
        },
        childrenCategories: [
          {
            count: 3,
            updateDate: '',
            categoryId: 10,
            categoryCode: '32',
            isDisplayed: true,
            content: {
              name: 'Tents',
              slug: 'tents',
              description: '',
            },
            childrenCategories: [],
          },
          {
            count: 12,
            updateDate: '',
            categoryId: 11,
            categoryCode: '34',
            isDisplayed: true,
            content: {
              name: 'Jackets',
              slug: 'jackets',
              description: '',
            },
            childrenCategories: [],
          },
          {
            count: 3,
            updateDate: '',
            categoryId: 6,
            categoryCode: '36',
            isDisplayed: true,
            content: {
              name: 'Backpacks',
              slug: 'backpacks',
              description: '',
            },
            childrenCategories: [],
          },
          {
            count: 3,
            updateDate: '',
            categoryId: 8,
            categoryCode: '37',
            isDisplayed: true,
            content: {
              name: 'Shoes',
              slug: 'shoes',
              description: '',
            },
            childrenCategories: [],
          },
        ],
      },
      {
        count: 15,
        updateDate: '',
        categoryId: 5,
        categoryCode: '40',
        isDisplayed: true,
        content: {
          name: 'Womens',
          slug: 'womens',
          description: '',
        },
        childrenCategories: [
          {
            count: 11,
            updateDate: '',
            categoryId: 18,
            categoryCode: '51',
            isDisplayed: true,
            content: {
              name: 'Tops',
              slug: 'tops',
              description: '',
            },
            childrenCategories: [],
          },
          {
            count: 3,
            updateDate: '',
            categoryId: 20,
            categoryCode: '50',
            isDisplayed: true,
            content: {
              name: 'Footwear',
              slug: 'footwear',
              description: '',
            },
            childrenCategories: [],
          },
          {
            count: 1,
            updateDate: '',
            categoryId: 19,
            categoryCode: '49',
            isDisplayed: true,
            content: {
              name: 'Bottoms',
              slug: 'bottoms',
              description: '',
            },
            childrenCategories: [],
          },
        ],
      },
      {
        count: 3,
        updateDate: '',
        categoryId: 4,
        categoryCode: '30',
        isDisplayed: true,
        content: {
          name: 'Biking',
          slug: 'biking',
          description: '',
        },
        childrenCategories: [
          {
            count: 1,
            updateDate: '',
            categoryId: 14,
            categoryCode: '42',
            isDisplayed: true,
            content: {
              name: 'Mountain',
              slug: 'mountain',
              description: '',
            },
            childrenCategories: [],
          },
          {
            count: 1,
            updateDate: '',
            categoryId: 22,
            categoryCode: '47',
            isDisplayed: true,
            content: {
              name: 'Road',
              slug: 'road',
              description: '',
            },
            childrenCategories: [],
          },
          {
            count: 1,
            updateDate: '',
            categoryId: 16,
            categoryCode: '48',
            isDisplayed: true,
            content: {
              name: 'Hybrid',
              slug: 'hybrid',
              description: '',
            },
            childrenCategories: [],
          },
        ],
      },
      {
        count: 8,
        updateDate: '',
        categoryId: 12,
        categoryCode: 'K',
        isDisplayed: true,
        content: {
          name: 'Kids',
          slug: 'kids',
          description: '',
        },
        childrenCategories: [
          {
            count: 4,
            updateDate: '',
            categoryId: 25,
            categoryCode: 'KA',
            isDisplayed: true,
            content: {
              name: 'Active',
              slug: 'active',
              description: 'because your kids have way more energy than you',
            },
            childrenCategories: [
              {
                count: 0,
                updateDate: '',
                categoryId: 40,
                categoryCode: 'KAT',
                isDisplayed: true,
                content: {
                  name: 'Tops',
                  slug: 'tops',
                  description: '',
                },
                childrenCategories: [],
              },
              {
                count: 1,
                updateDate: '',
                categoryId: 36,
                categoryCode: 'KAB',
                isDisplayed: true,
                content: {
                  name: 'Bottoms',
                  slug: 'bottoms',
                  description: '',
                },
                childrenCategories: [],
              },
              {
                count: 3,
                updateDate: '',
                categoryId: 42,
                categoryCode: 'KAF',
                isDisplayed: true,
                content: {
                  name: 'Footwear',
                  slug: 'footwear',
                  description: '',
                },
                childrenCategories: [],
              },
            ],
          },
          {
            count: 4,
            updateDate: '',
            categoryId: 26,
            categoryCode: 'KC',
            isDisplayed: true,
            content: {
              name: 'Casual',
              slug: 'casual',
              description: "because nap time is a parent's best friend",
            },
            childrenCategories: [
              {
                count: 0,
                updateDate: '',
                categoryId: 53,
                categoryCode: 'KCT',
                isDisplayed: true,
                content: {
                  name: 'Tops',
                  slug: 'tops',
                  description: '',
                },
                childrenCategories: [],
              },
              {
                count: 1,
                updateDate: '',
                categoryId: 48,
                categoryCode: 'KCB',
                isDisplayed: true,
                content: {
                  name: 'Bottoms',
                  slug: 'bottoms',
                  description: '',
                },
                childrenCategories: [],
              },
              {
                count: 3,
                updateDate: '',
                categoryId: 49,
                categoryCode: 'KCF',
                isDisplayed: true,
                content: {
                  name: 'Footwear',
                  slug: 'footwear',
                  description: '',
                },
                childrenCategories: [],
              },
            ],
          },
          {
            count: 0,
            updateDate: '',
            categoryId: 24,
            categoryCode: 'KS',
            isDisplayed: true,
            content: {
              name: 'Swim',
              slug: 'swim',
              description: "there's always that kid who loves to bellyflop",
            },
            childrenCategories: [],
          },
        ],
      },
      {
        count: 5,
        updateDate: '',
        categoryId: 13,
        categoryCode: '45',
        isDisplayed: true,
        content: {
          name: 'Pets',
          slug: 'pets',
          description: '',
        },
        childrenCategories: [],
      },
      {
        count: 6,
        updateDate: '',
        categoryId: 27,
        categoryCode: '28',
        isDisplayed: true,
        content: {
          name: 'Kayaking',
          slug: 'kayaking',
          description: '',
        },
        childrenCategories: [
          {
            count: 3,
            updateDate: '',
            categoryId: 39,
            categoryCode: '33',
            isDisplayed: true,
            content: {
              name: 'Kayaks',
              slug: 'kayaks',
              description: '',
            },
            childrenCategories: [],
          },
          {
            count: 3,
            updateDate: '',
            categoryId: 37,
            categoryCode: '35',
            isDisplayed: true,
            content: {
              name: 'Paddles',
              slug: 'paddles',
              description: '',
            },
            childrenCategories: [],
          },
        ],
      },
      {
        count: 7,
        updateDate: '',
        categoryId: 3,
        categoryCode: '29',
        isDisplayed: true,
        content: {
          name: 'Skiinggg',
          slug: 'skiing',
          description: 'skiis and stuff',
        },
        childrenCategories: [
          {
            count: 2,
            updateDate: '',
            categoryId: 7,
            categoryCode: '38',
            isDisplayed: true,
            content: {
              name: 'Skis',
              slug: 'skis',
              description: '',
            },
            childrenCategories: [],
          },
          {
            count: 3,
            updateDate: '',
            categoryId: 9,
            categoryCode: '39',
            isDisplayed: true,
            content: {
              name: 'Accessories',
              slug: 'accessories',
              description: '',
            },
            childrenCategories: [],
          },
        ],
      },
      {
        count: 42,
        updateDate: '',
        categoryId: 23,
        categoryCode: '46',
        isDisplayed: true,
        content: {
          name: 'New Products!',
          slug: 'new-products-',
          description: '',
        },
        childrenCategories: [],
      },
      {
        count: 2,
        updateDate: '',
        categoryId: 51,
        categoryCode: '67',
        isDisplayed: true,
        content: {
          name: 'Clearance',
          slug: 'clearance',
          description: '',
        },
        childrenCategories: [],
      },
    ] as PrCategory[],
    totalCount: 10,
  },
}
