import type { Checkout } from '@/lib/gql/types'
const checkoutResponse: Checkout = {
  id: '147542c811037d000104fe140000678b',
  originalCartId: '1475090c07e0230001d986680000678b',
  submittedDate: null,
  items: [
    {
      destinationId: null,
      fulfillmentLocationCode: 'SACRAMENTO',
      fulfillmentMethod: 'Ship',
      id: 'b22965e4f1aa46229038af4f00dd3a2c',
      total: 90,
      subtotal: 100,
      discountTotal: 10,
      quantity: 1,
      product: {
        productCode: 'BackP_024',
        name: 'Katahdin 50 Pack',
        description:
          'The JanSport Katahdin 50 pack for weekend trips has adjustable torso, vented back panel, great organization and plenty of straps, so you can wrangle your load while keeping the gear accessible.',
        imageUrl:
          '//cdn-sb.mozu.com/26507-41315/cms/41315/files/1b6b9ecd-912a-412f-8d11-c2660d265aff',
        options: [],
        properties: [],
        sku: null,
        price: {
          price: 100,
          salePrice: null,
        },
        categories: [
          {
            id: 19,
          },
          {
            id: 36,
          },
          {
            id: 333,
          },
          {
            id: 359,
          },
        ],
      },
    },
  ],
  groupings: [
    {
      id: '40e116b8adcb469d87d6462c21b54e2b',
      destinationId: null,
      fulfillmentMethod: 'Ship',
      orderItemIds: ['b22965e4f1aa46229038af4f00dd3a2c'],
      shippingMethodCode: null,
      shippingMethodName: null,
      standaloneGroup: false,
      shippingDiscounts: [],
      handlingDiscounts: [],
      dutyAmount: null,
      dutyTotal: 0,
      shippingAmount: 0,
      shippingSubTotal: 0,
      itemLevelShippingDiscountTotal: 0,
      orderLevelShippingDiscountTotal: 0,
      shippingTax: null,
      shippingTaxTotal: 0,
      shippingTotal: 0,
      handlingAmount: null,
      handlingSubTotal: 0,
      itemLevelHandlingDiscountTotal: 0,
      orderLevelHandlingDiscountTotal: 0,
      handlingTax: null,
      handlingTaxTotal: 0,
      handlingTotal: 0,
      taxData: null,
    },
  ],
  destinations: [],
  payments: [],
  amountRemainingForPayment: 90,
  acceptsMarketing: false,
  customerAccountId: null,
  email: null,
  customerTaxId: null,
  isTaxExempt: false,
  currencyCode: 'USD',
  priceListCode: '',
  attributes: null,
  shopperNotes: null,
  availableActions: ['SubmitCheckout'],
  data: null,
  taxData: null,
  channelCode: 'RETAIL',
  locationCode: null,
  ipAddress: '',
  sourceDevice: null,
  visitId: null,
  webSessionId: null,
  customerInteractionType: 'Unknown',
  orderDiscounts: [],
  couponCodes: [],
  invalidCoupons: [],
  suggestedDiscounts: [],
  discountThresholdMessages: [],
  dutyTotal: 0,
  feeTotal: 0,
  subTotal: 100,
  itemLevelProductDiscountTotal: 10,
  orderLevelProductDiscountTotal: 0,
  itemTaxTotal: 0,
  itemTotal: 90,
  shippingSubTotal: 0,
  itemLevelShippingDiscountTotal: 0,
  orderLevelShippingDiscountTotal: 0,
  shippingTaxTotal: 0,
  shippingTotal: 0,
  handlingSubTotal: 0,
  itemLevelHandlingDiscountTotal: 0,
  orderLevelHandlingDiscountTotal: 0,
  handlingTaxTotal: 0,
  handlingTotal: 0,
  total: 90,
  siteId: 0,
  tenantId: 0,
}
export const checkoutMock: { checkout: Checkout } = {
  checkout: checkoutResponse,
}

export const checkoutCouponMock: { updateCheckoutCoupon: Checkout } = {
  updateCheckoutCoupon: checkoutResponse,
}
