import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import Head from 'next/head'

import nextI18NextConfig from '../next-i18next.config'
import getCategoryTree from '@/lib/api/operations/get-category-tree'

import type { CategoryCollection } from '@/lib/gql/types'
import type { NextPage, GetStaticPropsContext } from 'next'

export async function getStaticProps(context: GetStaticPropsContext) {
  const { locale } = context
  const categoriesTree: CategoryCollection = await getCategoryTree()

  return {
    props: {
      categoriesTree,
      ...(await serverSideTranslations(locale as string, ['common'], nextI18NextConfig)),
    },
  }
}

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  )
}

export default Home
