export { default as ProductDetailTemplate } from './ProductDetailTemplate'
export { default as ProductListingTemplate } from './ProductListingTemplate'
export { default as CartTemplate } from './CartTemplate'
export { default as CheckoutTemplate } from './Checkout/Checkout'
export { default as MyAccountTemplate } from './MyAccountTemplate'
