export { default as ProductListingTemplate } from './ProductListingTemplate/ProductListingTemplate'
export { default as ProductDetailTemplate } from './ProductDetail/ProductDetailTemplate'
export { default as CartTemplate } from './CartTemplate/CartTemplate'
export { default as CheckoutTemplate } from './Checkout/Checkout'
export { default as MyAccountTemplate } from './MyAccountTemplate/MyAccountTemplate'
