export { default as ProductListingTemplate } from './ProductListingTemplate/ProductListingTemplate'
export { default as ProductDetailTemplate } from './ProductDetail/ProductDetailTemplate'
export { default as CartTemplate } from './CartTemplate'
export { default as CheckoutTemplate } from './CheckoutTemplate'
export { default as MyAccountTemplate } from './MyAccountTemplate'
