name: Commitlint
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  lint:
    name: Validate Pull Request Name (conventional-commit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install --save-dev @commitlint/config-conventional
      - uses: wagoid/commitlint-github-action@v6
