name: Commitlint
on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  commitlint:
    name: Validate Pull Request Name (conventional-commit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wagoid/commitlint-github-action@v6
